---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:
  MAVEN_REPO_MIRROR:
  MAVEN_REPO_USERNAME:
  MAVEN_REPO_PASSWORD:

inputs:
- name: pipeline
- name: concourse-commons
- name: project
- name: version

outputs:
- name: build-output

run:
  path: concourse-commons/scripts/build-maven.sh
