---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: pipeline
- name: concourse-commons
- name: project
- name: version

outputs:
- name: build-output

run:
  path: concourse-commons/scripts/build-maven.sh
