---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/lotc
    tag: 'latest'

inputs:
- name: pipeline
- name: release

outputs:
- name: generate-manifest-output

params:
  CF_API_URL:
  CF_SKIP_SSL:
  CF_ARTIFACT_ID:
  CF_APP_NAME:
  CF_APP_HOST:
  CF_APP_SERVICES:
  CF_APP_MEMORY:
  CF_APP_INSTANCES:
  CF_APP_TIMEOUT:

run:
  path: concourse-commons/scripts/generate-manifest.sh
