---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
- name: concourse-commons
- name: project

outputs:
- name: generate-commitish-output

run:
  path: concourse-commons/scripts/generate-commitish.sh
